openapi: 3.0.2
info:
  title: Covid-19 Tracker (Java)
  description: Covid-19 Tracker Report Microservice
  version: '0.1'
servers:
  - url: http://localhost:/8080
tags:
  - name: Cases
    description: cases of covid with daily/monthly
  - name: Vacctination
    description: vaccination management

paths:
  /cases-of-covid:
    post:
      tags:
        - Cases
      summary: Create cases covid
      operationId: saveAllCases
      requestBody:
        description: patient list object that needs to be added
        content:
          application/json:
            schema:
              type: array
              description: Found objects
              items:
                $ref: '#/components/schemas/PatientPostDto'
      responses:
        201:
          description: User Created
          content:
            application/json:
              schema:
                type: integer
        default:
          $ref: '#/components/responses/Error'
    put:
      tags:
        - Cases
      summary: Create cases covid
      operationId: updateAllCases
      requestBody:
        description: patient list object that needs to be added
        content:
          application/json:
            schema:
              type: array
              description: Found objects
              items:
                $ref: '#/components/schemas/PatientPostDto'
      responses:
        201:
          description: User Created
          content:
            application/json:
              schema:
                type: integer
        default:
          $ref: '#/components/responses/Error'

components:
  schemas:
    PatientPostDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique user ID
        lastName:
          type: string
          description: lastName patient
          example: lorant
        firstName:
          type: string
          description: patient firstName
          example: Martin
        birthDate:
          type: string
          format: date
          description: birthDate
          example: "2021-01-30"
        address:
          type: string
          description: user address
          example: 24 Rue Saint-Lazare
        cellPhone:
          type: string
          description: user cell Phone
          example: 00216 22 150 423
        testDate:
          type: string
          format: date-time
          description: date of test
          example: "2021-01-30T08:30:00Z"
        resultTest:
          $ref: '#/components/schemas/ResultTest'
        country:
          $ref: '#/components/schemas/Country'
        createdAt:
          type: string
          format: date-time
          description: Creation date of conversation
          example: "2021-01-30T08:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Update date of conversation
          example: "2021-01-30T08:30:00Z"
    Country:
      type: string
      enum:
        - FRANCE
        - TUNISIA
        - MEXICO
        - POLAND
        - UKRAINE
    ResultTest:
      type: string
      enum:
        - POSITIVE
        - NEGATIVE
    Error:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

  responses:
    Error:
      description: Error accessing the service consistent with http status code
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InvalidInput:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Unable to find resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  parameters:
    patientId:
      in: query
      name: patientId
      schema:
        type: string
        default: 205
      description: The patient id